name: Apocalypse
version: 1.0
author: Group_1
main: group.wilson.apocalypse.Main
commands:
  chest:
    description: gives the user a chest
    usage: /chest can only be used every minute!
  leaderboard:
    description: displays zombie kill leaderboard
    usage: /leaderboard
  kills:
    description: displays zombie kills
    usage: /kills